YA_HOME_PAGE = 'ya.ru'
DZEN_HOME_PAGE = 'dzen.ru'
YANDEX_CAPTCHA_PAGE = 'yandex.ru'
YA_SCOOTER_HOME_PAGE = 'https://qa-scooter.praktikum-services.ru'
YA_SCOOTER_ORDER_PAGE = f'{YA_SCOOTER_HOME_PAGE}/order'
YA_SCOOTER_ORDER_STATUS_PAGE = f'{YA_SCOOTER_HOME_PAGE}/track'
